# CMake generated Testfile for 
# Source directory: /Users/ben/Desktop/BA/src/DUNE/dune-common/dune/common/simd/test
# Build directory: /Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/dune/common/simd/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(looptest "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/dune/common/simd/test/looptest")
set_tests_properties(looptest PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/dune/common/simd/test/looptest" SKIP_RETURN_CODE "77" TIMEOUT "300" WORKING_DIRECTORY "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/dune/common/simd/test" _BACKTRACE_TRIPLES "/Users/ben/Desktop/BA/src/DUNE/dune-common/cmake/modules/DuneTestMacros.cmake;414;_add_test;/Users/ben/Desktop/BA/src/DUNE/dune-common/dune/common/simd/test/CMakeLists.txt;34;dune_add_test;/Users/ben/Desktop/BA/src/DUNE/dune-common/dune/common/simd/test/CMakeLists.txt;0;")
add_test(standardtest "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/dune/common/simd/test/standardtest")
set_tests_properties(standardtest PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/dune/common/simd/test/standardtest" SKIP_RETURN_CODE "77" TIMEOUT "300" WORKING_DIRECTORY "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/dune/common/simd/test" _BACKTRACE_TRIPLES "/Users/ben/Desktop/BA/src/DUNE/dune-common/cmake/modules/DuneTestMacros.cmake;414;_add_test;/Users/ben/Desktop/BA/src/DUNE/dune-common/dune/common/simd/test/CMakeLists.txt;59;dune_add_test;/Users/ben/Desktop/BA/src/DUNE/dune-common/dune/common/simd/test/CMakeLists.txt;0;")
add_test(vcarraytest "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/dune/common/simd/test/vcarraytest")
set_tests_properties(vcarraytest PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/dune/common/simd/test/vcarraytest" SKIP_RETURN_CODE "77" TIMEOUT "300" WORKING_DIRECTORY "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/dune/common/simd/test" _BACKTRACE_TRIPLES "/Users/ben/Desktop/BA/src/DUNE/dune-common/cmake/modules/DuneTestMacros.cmake;414;_add_test;/Users/ben/Desktop/BA/src/DUNE/dune-common/dune/common/simd/test/CMakeLists.txt;85;dune_add_test;/Users/ben/Desktop/BA/src/DUNE/dune-common/dune/common/simd/test/CMakeLists.txt;0;")
add_test(vcvectortest "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/dune/common/simd/test/vcvectortest")
set_tests_properties(vcvectortest PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/dune/common/simd/test/vcvectortest" SKIP_RETURN_CODE "77" TIMEOUT "300" WORKING_DIRECTORY "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/dune/common/simd/test" _BACKTRACE_TRIPLES "/Users/ben/Desktop/BA/src/DUNE/dune-common/cmake/modules/DuneTestMacros.cmake;414;_add_test;/Users/ben/Desktop/BA/src/DUNE/dune-common/dune/common/simd/test/CMakeLists.txt;108;dune_add_test;/Users/ben/Desktop/BA/src/DUNE/dune-common/dune/common/simd/test/CMakeLists.txt;0;")
