# CMake generated Testfile for 
# Source directory: /Users/ben/Desktop/BA/src/DUNE/dune-common/dune/python/test
# Build directory: /Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/dune/python/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(pythontests "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/run-in-dune-env" "python" "pythontests.py")
set_tests_properties(pythontests PROPERTIES  LABELS "quick;python" PROCESSORS "1" SKIP_RETURN_CODE "77" TIMEOUT "3600" WORKING_DIRECTORY "/Users/ben/Desktop/BA/src/DUNE/dune-common/dune/python/test" _BACKTRACE_TRIPLES "/Users/ben/Desktop/BA/src/DUNE/dune-common/cmake/modules/DuneTestMacros.cmake;414;_add_test;/Users/ben/Desktop/BA/src/DUNE/dune-common/cmake/modules/DunePythonTestCommand.cmake;102;dune_add_test;/Users/ben/Desktop/BA/src/DUNE/dune-common/dune/python/test/CMakeLists.txt;4;dune_python_add_test;/Users/ben/Desktop/BA/src/DUNE/dune-common/dune/python/test/CMakeLists.txt;0;")
add_test(pythontests-mpi-2 "/usr/local/bin/mpiexec" "-n" "2" "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/run-in-dune-env" "python" "pythontests.py")
set_tests_properties(pythontests-mpi-2 PROPERTIES  LABELS "quick;python" PROCESSORS "2" SKIP_RETURN_CODE "77" TIMEOUT "3600" WORKING_DIRECTORY "/Users/ben/Desktop/BA/src/DUNE/dune-common/dune/python/test" _BACKTRACE_TRIPLES "/Users/ben/Desktop/BA/src/DUNE/dune-common/cmake/modules/DuneTestMacros.cmake;414;_add_test;/Users/ben/Desktop/BA/src/DUNE/dune-common/cmake/modules/DunePythonTestCommand.cmake;102;dune_add_test;/Users/ben/Desktop/BA/src/DUNE/dune-common/dune/python/test/CMakeLists.txt;4;dune_python_add_test;/Users/ben/Desktop/BA/src/DUNE/dune-common/dune/python/test/CMakeLists.txt;0;")
add_test(test_embed1 "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/run-in-dune-env" "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/dune/python/test/test_embed1")
set_tests_properties(test_embed1 PROPERTIES  LABELS "quick" PROCESSORS "1" REQUIRED_FILES "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/dune/python/test/test_embed1" SKIP_RETURN_CODE "77" TIMEOUT "300" WORKING_DIRECTORY "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/dune/python/test" _BACKTRACE_TRIPLES "/Users/ben/Desktop/BA/src/DUNE/dune-common/cmake/modules/DuneTestMacros.cmake;414;_add_test;/Users/ben/Desktop/BA/src/DUNE/dune-common/dune/python/test/CMakeLists.txt;11;dune_add_test;/Users/ben/Desktop/BA/src/DUNE/dune-common/dune/python/test/CMakeLists.txt;0;")
add_test(test_embed2 "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/run-in-dune-env" "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/dune/python/test/test_embed2")
set_tests_properties(test_embed2 PROPERTIES  LABELS "quick" PROCESSORS "1" REQUIRED_FILES "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/dune/python/test/test_embed2" SKIP_RETURN_CODE "77" TIMEOUT "300" WORKING_DIRECTORY "/Users/ben/Desktop/BA/src/DUNE/release-build/dune-common/dune/python/test" _BACKTRACE_TRIPLES "/Users/ben/Desktop/BA/src/DUNE/dune-common/cmake/modules/DuneTestMacros.cmake;414;_add_test;/Users/ben/Desktop/BA/src/DUNE/dune-common/dune/python/test/CMakeLists.txt;19;dune_add_test;/Users/ben/Desktop/BA/src/DUNE/dune-common/dune/python/test/CMakeLists.txt;0;")
